### ISSUE TITLE
MacOS error: `ld: library not found for -lrdkafka`

### ISSUE THREAD

**Issue by aSemy** [icemachined/kafka-kotlin-native#7]
When I run `./gradlew assemble` on my Mac, I get an error:

```kotlin
plugins {
  kotlin("multiplatform") version "1.7.21"
}

group = "demo"
version = "0.0.1"

kotlin {

  macosX64("native") {
    binaries {
      executable {
        entryPoint = "main"
      }
    }
  }

  sourceSets {
    val nativeMain by getting {

      dependencies {
        implementation(platform(kotlin("bom")))

        implementation("com.icemachined:kafka-client:0.2.0")
      }
    }

    val nativeTest by getting {
      dependencies {
      }
    }
  }
}
```

When I checkout kafka-kotlin-native and run `./gradlew assemble`, it fails, and the output includes this stacktrace:

```

> Task :kafka-client:cinteropLibrdkafkaMacosX64
Exception in thread "main" java.lang.Error: /var/folders/wl/2bzbzknd077dyh2ww_6xjty80000gp/T/3344506493200322852.c:1:10: fatal error: 'librdkafka/rdkafka.h' file not found
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:274)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:1196)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:1185)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:1181)
	at org.jetbrains.kotlin.native.interop.gen.jvm.DefaultPlugin.buildNativeIndex(Plugins.kt:33)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:289)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLibSafe(main.kt:214)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:80)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:40)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:62)
```

**Comment by icemachined** [comment]
1. you need to include this library in commonMain dependenies, see example https://github.com/saveourtool/kafka-client-test/blob/main/build.gradle.kts
2. librdkafka/rdkafka.h' file not found, you need to install librdkafka first on mac, see how it is done in https://github.com/icemachined/kafka-kotlin-native/blob/main/.github/workflows/build_and_test.yml
